version: '3'

services:
  squid:
    build: .
    ports:
      - "127.0.0.1:3128:3128"
    volumes:
      - squid_cache:/var/spool/squid
    environment:
      - SQUID_CACHE_DIR=/var/spool/squid/cache
      - SQUID_LOG_DIR=/var/log/squid
      - SQUID_USER=proxy

volumes:
  squid_cache:
